server:
  port: 7001

eureka:
  instance:
    hostname: localhost #Eureka服务端的实例名称
#    prefer-ip-address: true
  client:
    register-with-eureka: false #表示是否向Eureka注册中心注册自己
    fetch-registry: false #false表示自己为注册中心
    service-url: #监控页面
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#spring:
#  freemarker:
#    prefer-file-system-access: false
